common/swupdate: set GRUBENV_PATH to fix updates with hawkbit server
This sets the SWUpdate's CONFIG_GRUBENV_PATH so that when an update
is performed via HawkBit Server, it looks for the right grubenv file
to save_state into rather than going for the GRUBENV_PATH_DEFAULT
which does not exist in our case. Otherwise, update fails saying:

 ERROR: Failed to open grubenv file: /boot/efi/EFI/BOOT/grub/grubenv
 ERROR: Cannot persistently store update state.

Signed-off-by: Arsalan H. Awan <Arsalan_Awan@mentor.com>